/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nezet;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import modell.LadaOsztaly;
import modell.Szinek;

/**
 *
 * @author matex
 */
public class KincsKeresiGui extends javax.swing.JFrame {

    /**
     * Creates new form KincsKeresiGui
     */
    public KincsKeresiGui() {
        initComponents();
        jatek();
    }

    private void jatek() {
        tartalomlb.setText("");
        LadaOsztaly aranyLada = new LadaOsztaly(Szinek.ARANY);
        LadaOsztaly ezustLada = new LadaOsztaly(Szinek.EZUST);
        LadaOsztaly bronzLada = new LadaOsztaly(Szinek.BRONZ);
        szinEsKepAllitas(aranyLada, aranybtn);
        szinEsKepAllitas(ezustLada, ezustbtn);
        szinEsKepAllitas(bronzLada, bronzbtn);
        addLadaToButton(aranyLada, aranybtn);
        addLadaToButton(ezustLada, ezustbtn);
        addLadaToButton(bronzLada, bronzbtn);
        allitasKiiratas(aranyLada, aranyAll);
        allitasKiiratas(ezustLada, ezustAll);
        allitasKiiratas(bronzLada, bronzAll);
    }

    private void allitasKiiratas(LadaOsztaly lada, JLabel allitas) {
        allitas.setText(lada.Allitas());
    }

    private void szinEsKepAllitas(LadaOsztaly lada, JButton gomb) {
        String szin = "";
        if (lada.getSzin() == Szinek.ARANY) {
            szin = "Arany";
        } else if (lada.getSzin() == Szinek.EZUST) {
            szin = "Ezüst";
        } else if (lada.getSzin() == Szinek.BRONZ) {
            szin = "Bronz";
        }
        kepAllitas(gomb, "/nezetKep/ladaKep.jpg");
        gomb.setText(szin);
    }

    private void addLadaToButton(LadaOsztaly lada, JButton gomb) {
        gomb.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tartalomlb.setText(lada.isKincsnalavan() ? "Kincs" : "Üres");
                String kepHelye = lada.isKincsnalavan() ? "/nezetKep/kincsLada.png" : "/nezetKep/uresLada.jpg";
                kepAllitas(gomb, kepHelye);
            }
        });
    }

    private void kepAllitas(JButton gomb, String kepHelye) {
        try {
            Image img = ImageIO.read(getClass().getResource(kepHelye));
            gomb.setIcon(new ImageIcon(img));
            gomb.setText("");
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        aranybtn = new javax.swing.JButton();
        ezustbtn = new javax.swing.JButton();
        bronzbtn = new javax.swing.JButton();
        aranyAll = new javax.swing.JLabel();
        ezustAll = new javax.swing.JLabel();
        bronzAll = new javax.swing.JLabel();
        ujjatekbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tartalomlb = new javax.swing.JLabel();

        jButton3.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(2, 3));

        aranybtn.setText("Arany");
        jPanel1.add(aranybtn);

        ezustbtn.setText("Ezüst");
        jPanel1.add(ezustbtn);

        bronzbtn.setText("Bronz");
        jPanel1.add(bronzbtn);

        aranyAll.setText("jLabel3");
        jPanel1.add(aranyAll);

        ezustAll.setText("jLabel4");
        jPanel1.add(ezustAll);

        bronzAll.setText("jLabel5");
        jPanel1.add(bronzAll);

        ujjatekbtn.setText("Új játék");
        ujjatekbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ujjatekbtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Láda tartalma:");

        tartalomlb.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ujjatekbtn)
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tartalomlb, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 709, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ujjatekbtn)
                    .addComponent(jLabel1)
                    .addComponent(tartalomlb))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ujjatekbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ujjatekbtnActionPerformed
        jatek();
    }//GEN-LAST:event_ujjatekbtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aranyAll;
    private javax.swing.JButton aranybtn;
    private javax.swing.JLabel bronzAll;
    private javax.swing.JButton bronzbtn;
    private javax.swing.JLabel ezustAll;
    private javax.swing.JButton ezustbtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tartalomlb;
    private javax.swing.JButton ujjatekbtn;
    // End of variables declaration//GEN-END:variables
}
